/**
 * @preserve
 * @source: https://raw.githubusercontent.com/lunarcloud/gameinputjs/master/gameinput.models.js
 * @license magnet:?xt=urn:btih:d3d9a9a6595521f9666a5e94cc830dab83b65699&dn=expat.txt MIT (Expat) License
 */
import { GameInputModel, GamepadAPI, GameInputSchemaType, SchemaAxisButton } from './gameinput.types'

const frenchVRStickDeadzone = 0.6;
const frenchVRStickThreshold = 0.8;

const GravisGamepadProSchema = new GamepadAPI(undefined,
    /* d_up */  new SchemaAxisButton(-2),
    /* d_down */  new SchemaAxisButton(2),
    /* d_left */  new SchemaAxisButton(-1),
    /* d_right */  new SchemaAxisButton(1),
    /* menu */  10,
    /* button0 */  2,
    /* button1 */  3,
    /* button2 */  1,
    /* button3 */  4,
    /* l_up */  undefined,
    /* l_down */  undefined,
    /* l_left */  undefined,
    /* l_right */  undefined,
    /* r_up */  new SchemaAxisButton(-4),
    /* r_down */  new SchemaAxisButton(4),
    /* r_left */  new SchemaAxisButton(-3),
    /* r_right */  new SchemaAxisButton(3),
    /* l_button */  5,
    /* r_button */  6,
    /* l_trigger */  7,
    /* r_trigger */  8
);

/*
    * "HuiJia  PS/SS/N64 Joypad to USB BOX (Vendor: 0925 Product: 1700)"
    * Force to manually configure this multiple-configuration adapter instead of assuming which adapter port you're using
    */

const GameInputModels = [
    new GameInputModel(
        GameInputSchemaType.Hedgehog,
        "xbox360",
        "Xbox 360 Controller (XInput STANDARD GAMEPAD)",
        "Windows",
        GamepadAPI.Standard
    ),
    new GameInputModel(
        GameInputSchemaType.Plumber,
        "nintendo-generic",
        "0925-8866-SFC/USB Pad",
        "Windows",
        new GamepadAPI(undefined,
            new SchemaAxisButton(-2),
            new SchemaAxisButton(2),
            new SchemaAxisButton(-1),
            new SchemaAxisButton(1),
            8,
            2,1,4,3,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            5, 6, undefined, undefined
    )),
    new GameInputModel(
        GameInputSchemaType.Plumber,
        "nintendo-generic",
        "SFC/USB Pad (Vendor: 0925 Product: 8866)",
        "Windows",
        new GamepadAPI(undefined,
            new SchemaAxisButton(-2),
            new SchemaAxisButton(2),
            new SchemaAxisButton(-1),
            new SchemaAxisButton(1),
            8,
            2,1,4,3,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            5, 6, undefined, undefined
    )),
    new GameInputModel(
        GameInputSchemaType.Hedgehog,
        "xbox360",
        "Xbox 360 Wireless Receiver (Vendor: 0000 Product: 0000)",
        "Linux",
        new GamepadAPI(undefined,
            16,17,14,15,
            10,
            2,1,4,3,
            new SchemaAxisButton(-2),
            new SchemaAxisButton(2),
            new SchemaAxisButton(-1),
            new SchemaAxisButton(1),
            new SchemaAxisButton(-4),
            new SchemaAxisButton(4),
            new SchemaAxisButton(-3),
            new SchemaAxisButton(3),
            5,6,7,8
    )),
    new GameInputModel(
        GameInputSchemaType.Hedgehog,
        "xbox360",
        "0000-0000-Xbox 360 Wireless Receiver",
        "Linux",
        new GamepadAPI(undefined,
            16,17,14,15,
            10,
            1,2,3,4,
            new SchemaAxisButton(-2),
            new SchemaAxisButton(2),
            new SchemaAxisButton(-1),
            new SchemaAxisButton(1),
            new SchemaAxisButton(-4),
            new SchemaAxisButton(4),
            new SchemaAxisButton(-3),
            new SchemaAxisButton(3),
            5,6,7,8
    )),
    new GameInputModel(
        GameInputSchemaType.Ragdoll4,
        "ds4",
        "Wireless Controller (STANDARD GAMEPAD Vendor: 054c Product: 05c4)",
        "Windows",
        GamepadAPI.Standard
    ),
    new GameInputModel(
        GameInputSchemaType.Ragdoll4,
        "ds4",
        "Wireless Controller (STANDARD GAMEPAD Vendor: 054c Product: 05c4)",
        "macOS",
        GamepadAPI.Standard
    ),
    new GameInputModel(
        GameInputSchemaType.Ragdoll4,
        "ds4",
        "054c-05c4-Wireless Controller",
        "Windows",
        new GamepadAPI(undefined,
            15, 16, 17, 18,
            10,
            2, 3, 1, 4,
            new SchemaAxisButton(-2),
            new SchemaAxisButton(2),
            new SchemaAxisButton(-1),
            new SchemaAxisButton(1),
            new SchemaAxisButton(-6),
            new SchemaAxisButton(6),
            new SchemaAxisButton(-3),
            new SchemaAxisButton(3),
            5, 6, 7, 8
    )),
    new GameInputModel(
        GameInputSchemaType.Hedgehog,
        "xbox360",
        "©Microsoft Corporation Controller (STANDARD GAMEPAD Vendor: 045e Product: 028e)",
        "Linux",
        GamepadAPI.Standard
    ),
    new GameInputModel(
        GameInputSchemaType.Hedgehog,
        "xbox360",
        "Performance Designed Products Afterglow Gamepad for Xbox 360 (STANDARD GAMEPAD Vendor: 0e6f Product: 0213)",
        "Linux",
        new GamepadAPI("Afterglow Gamepad for Xbox 360",
            13,14,15,16,
            10,
            1,2,3,4,
            new SchemaAxisButton(-2),
            new SchemaAxisButton(2),
            new SchemaAxisButton(-1),
            new SchemaAxisButton(1),
            new SchemaAxisButton(-4),
            new SchemaAxisButton(4),
            new SchemaAxisButton(-3),
            new SchemaAxisButton(3),
            5, 6, 7, 8
    )),
    new GameInputModel(
        GameInputSchemaType.Hedgehog,
        "xbox360",
        "Performance Designed Products Afterglow Gamepad for Xbox 360 (Vendor: 0e6f Product: 0213)",
        "Linux",
        new GamepadAPI("Afterglow Gamepad for Xbox 360",
            new SchemaAxisButton(-8),
            new SchemaAxisButton(8),
            new SchemaAxisButton(-7),
            new SchemaAxisButton(7),
            8,
            1,2,3,4,
            new SchemaAxisButton(-2),
            new SchemaAxisButton(2),
            new SchemaAxisButton(-1),
            new SchemaAxisButton(1),
            new SchemaAxisButton(-5),
            new SchemaAxisButton(5),
            new SchemaAxisButton(-4),
            new SchemaAxisButton(4),
            5,
            6,
            new SchemaAxisButton(3),
            new SchemaAxisButton(6)
    )),
    new GameInputModel(
        GameInputSchemaType.Hedgehog,
        "xbox360",
        "0e6f-0213-Afterglow Gamepad for Xbox 360",
        "Linux",
        new GamepadAPI("Afterglow Gamepad for Xbox 360",
            new SchemaAxisButton(-8),
            new SchemaAxisButton(8),
            new SchemaAxisButton(-7),
            new SchemaAxisButton(7),
            8,
            1,2,3,4,
            new SchemaAxisButton(-2),
            new SchemaAxisButton(2),
            new SchemaAxisButton(-1),
            new SchemaAxisButton(1),
            new SchemaAxisButton(-5),
            new SchemaAxisButton(5),
            new SchemaAxisButton(-4),
            new SchemaAxisButton(4),
            5,
            6,
            new SchemaAxisButton(3),
            new SchemaAxisButton(6)
    )),
    new GameInputModel(
        GameInputSchemaType.Hedgehog,
        "dc",
        "HuiJia  USB GamePad (Vendor: 0e8f Product: 3013)",
        "Linux",
        new GamepadAPI(undefined,
            13, 15, 16, 14,
            10,
            1,2,3,4,
            new SchemaAxisButton(-2),
            new SchemaAxisButton(2),
            new SchemaAxisButton(-1),
            new SchemaAxisButton(1),
            undefined,
            undefined,
            undefined,
            undefined,
            undefined, undefined, 5, 6
    )),
    new GameInputModel(
        GameInputSchemaType.Hedgehog,
        "dc",
        "USB GamePad (Vendor: 0e8f Product: 3013)",
        "Windows",
        new GamepadAPI(undefined,
            13, 15, 16, 14,
            10,
            1,2,3,4,
            new SchemaAxisButton(-2),
            new SchemaAxisButton(2),
            new SchemaAxisButton(-1),
            new SchemaAxisButton(1),
            undefined,
            undefined,
            undefined,
            undefined,
            undefined, undefined, 5, 6
    )),
    new GameInputModel(
        GameInputSchemaType.Hedgehog,
        "dc",
        "USB GamePad (Vendor: 0e8f Product: 3013)",
        "macOS",
        new GamepadAPI(undefined,
        13, 15, 16, 14,
        10,
        1, 2, 3, 4,
        new SchemaAxisButton(-2),
        new SchemaAxisButton(2),
        new SchemaAxisButton(-1),
        new SchemaAxisButton(1),
        undefined,
        undefined,
        undefined,
        undefined,
        undefined, undefined, 5, 6
    )),
    new GameInputModel(
        GameInputSchemaType.Ragdoll,
        "ds3",
        "Sony PLAYSTATION(R)3 Controller (STANDARD GAMEPAD Vendor: 054c Product: 0268)",
        "Linux",
        GamepadAPI.Standard
    ),
    new GameInputModel(
        GameInputSchemaType.Ragdoll,
        "ds3",
        "054c-0268-Sony PLAYSTATION(R)3 Controller",
        "Linux",
        new GamepadAPI(undefined,
            5,7,8,6,
            4,
            15, 14, 16, 13,
            new SchemaAxisButton(-2),
            new SchemaAxisButton(2),
            new SchemaAxisButton(-1),
            new SchemaAxisButton(1),
            new SchemaAxisButton(-4),
            new SchemaAxisButton(4),
            new SchemaAxisButton(-3),
            new SchemaAxisButton(3),
            11,12,9,10
    )),
    new GameInputModel(
        GameInputSchemaType.Ragdoll4,
        "ds4",
        "Sony Computer Entertainment Wireless Controller (STANDARD GAMEPAD Vendor: 054c Product: 05c4)",
        "Linux",
        GamepadAPI.Standard
    ),
    new GameInputModel(
        GameInputSchemaType.Ragdoll4,
        "ds4",
        "054c-05c4-Sony Computer Entertainment Wireless Controller",
        "Linux",
        new GamepadAPI(undefined,
            new SchemaAxisButton(-8),
            new SchemaAxisButton(8),
            new SchemaAxisButton(-7),
            new SchemaAxisButton(7),
            10,
            2,3,1,4,
            new SchemaAxisButton(-2),
            new SchemaAxisButton(2),
            new SchemaAxisButton(-1),
            new SchemaAxisButton(1),
            new SchemaAxisButton(-6),
            new SchemaAxisButton(6),
            new SchemaAxisButton(-3),
            new SchemaAxisButton(3),
            5, 6, 7, 8
    )),
    new GameInputModel(
        GameInputSchemaType.Hedgehog,
        "joystick",
        "Mayflash Arcade Stick (Vendor: 0e8f Product: 0003)",
        "Windows",
        new GamepadAPI(undefined,
            new SchemaAxisButton(-2),
            new SchemaAxisButton(2),
            new SchemaAxisButton(-1),
            new SchemaAxisButton(1),
            10,
            1, 2, 3, 4,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            5, 6, 7, 8
    )),
    new GameInputModel(
        GameInputSchemaType.Hedgehog,
        "joystick",
        "PLAYSTATION(R)3 Controller (STANDARD GAMEPAD Vendor: 054c Product: 0268)", /* Mayflash Arcade Stick */
        "macOS",
        new GamepadAPI(undefined,
        13, 14, 15, 16,
        10,
        7, 1, 2, 8,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        5, 3, 4, 6
    )),
    new GameInputModel(
        GameInputSchemaType.Ragdoll,
        "joystick",
        "MY-POWER CO.,LTD. Mayflash Arcade Stick (STANDARD GAMEPAD Vendor: 0e8f Product: 0003)",
        "Linux",
        new GamepadAPI(undefined,
            new SchemaAxisButton(-3),
            new SchemaAxisButton(3),
            new SchemaAxisButton(-4),
            new SchemaAxisButton(4),
            10,
            4,2,1,3,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            7,8,5,6
    )),
    new GameInputModel(
        GameInputSchemaType.Ragdoll,
        "joystick",
        "0e8f-0003-MY-POWER CO.,LTD. Mayflash Arcade Stick",
        "Linux",
        new GamepadAPI(undefined,
            new SchemaAxisButton(-2),
            new SchemaAxisButton(2),
            new SchemaAxisButton(-1),
            new SchemaAxisButton(1),
            10,
            1,2,3,4,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            5,6,7,8
    )),
    new GameInputModel(
        GameInputSchemaType.Hedgehog,
        "generic",
        "Logitech Logitech Dual Action (Vendor: 046d Product: c216)", // DirectInput (XInput uses 'standard' mapping)
        "Linux",
        new GamepadAPI(undefined,
            /* d_up */  new SchemaAxisButton(-6),
            /* d_down */  new SchemaAxisButton(6),
            /* d_left */  new SchemaAxisButton(-5),
            /* d_right */  new SchemaAxisButton(5),
            /* menu */  10,
            /* button0 */  2,
            /* button1 */  3,
            /* button2 */  1,
            /* button3 */  4,
            /* l_up */  new SchemaAxisButton(-2),
            /* l_down */  new SchemaAxisButton(2),
            /* l_left */  new SchemaAxisButton(-1),
            /* l_right */  new SchemaAxisButton(1),
            /* r_up */  new SchemaAxisButton(-4),
            /* r_down */  new SchemaAxisButton(4),
            /* r_left */  new SchemaAxisButton(-3),
            /* r_right */  new SchemaAxisButton(3),
            /* l_button */  5,
            /* r_button */  6,
            /* l_trigger */  7,
            /* r_trigger */  8
    )),
    new GameInputModel(
        GameInputSchemaType.Hedgehog,
        "generic",
        "Logitech Gamepad F310 (Vendor: 046d Product: c21d)",
        "Linux",
        new GamepadAPI(undefined,
            /* d_up */  new SchemaAxisButton(-8),
            /* d_down */  new SchemaAxisButton(8),
            /* d_left */  new SchemaAxisButton(-7),
            /* d_right */  new SchemaAxisButton(7),
            /* menu */  8,
            /* button0 */  1,
            /* button1 */  2,
            /* button2 */  3,
            /* button3 */  4,
            /* l_up */  new SchemaAxisButton(-2),
            /* l_down */  new SchemaAxisButton(2),
            /* l_left */  new SchemaAxisButton(-1),
            /* l_right */  new SchemaAxisButton(1),
            /* r_up */  new SchemaAxisButton(-5),
            /* r_down */  new SchemaAxisButton(5),
            /* r_left */  new SchemaAxisButton(-4),
            /* r_right */  new SchemaAxisButton(4),
            /* l_button */  5,
            /* r_button */  6,
            /* l_trigger */  new SchemaAxisButton(3),
            /* r_trigger */  new SchemaAxisButton(6)
    )),
    new GameInputModel(
        GameInputSchemaType.Hedgehog,
        "generic",
        "046d-c21d-Logitech Gamepad F310", // XInput
        "Linux",
        new GamepadAPI(undefined,
            /* d_up */  new SchemaAxisButton(-8),
            /* d_down */  new SchemaAxisButton(8),
            /* d_left */  new SchemaAxisButton(-7),
            /* d_right */  new SchemaAxisButton(7),
            /* menu */  8,
            /* button0 */  1,
            /* button1 */  2,
            /* button2 */  3,
            /* button3 */  4,
            /* l_up */  new SchemaAxisButton(-2),
            /* l_down */  new SchemaAxisButton(2),
            /* l_left */  new SchemaAxisButton(-1),
            /* l_right */  new SchemaAxisButton(1),
            /* r_up */  new SchemaAxisButton(-5),
            /* r_down */  new SchemaAxisButton(5),
            /* r_left */  new SchemaAxisButton(-4),
            /* r_right */  new SchemaAxisButton(4),
            /* l_button */  5,
            /* r_button */  6,
            /* l_trigger */  new SchemaAxisButton(3),
            /* r_trigger */  new SchemaAxisButton(6)
    )),
    new GameInputModel(
        GameInputSchemaType.Hedgehog,
        "generic",
        "046d-c216-Logitech Logitech Dual Action", // DirectInput (XInput uses 'standard' mapping)
        "Linux",
        new GamepadAPI(undefined,
            /* d_up */  new SchemaAxisButton(-6),
            /* d_down */  new SchemaAxisButton(6),
            /* d_left */  new SchemaAxisButton(-5),
            /* d_right */  new SchemaAxisButton(5),
            /* menu */  10,
            /* button0 */  2,
            /* button1 */  3,
            /* button2 */  1,
            /* button3 */  4,
            /* l_up */  new SchemaAxisButton(-2),
            /* l_down */  new SchemaAxisButton(2),
            /* l_left */  new SchemaAxisButton(-1),
            /* l_right */  new SchemaAxisButton(1),
            /* r_up */  new SchemaAxisButton(-4),
            /* r_down */  new SchemaAxisButton(4),
            /* r_left */  new SchemaAxisButton(-3),
            /* r_right */  new SchemaAxisButton(3),
            /* l_button */  5,
            /* r_button */  6,
            /* l_trigger */  7,
            /* r_trigger */  8
    )),
    new GameInputModel(
        GameInputSchemaType.Ragdoll,
        "joystick",
        "Logitech Logitech Extreme 3D Pro (Vendor: 046d Product: c215)",
        "Linux",
        new GamepadAPI(undefined,
            new SchemaAxisButton(-6, 0.3),
            new SchemaAxisButton(6, 0.3),
            new SchemaAxisButton(-5, 0.3),
            new SchemaAxisButton(5, 0.3),
            12,
            1,2,3,4,
            new SchemaAxisButton(-2, 0.3),
            new SchemaAxisButton(2, 0.3),
            new SchemaAxisButton(-1, 0.3),
            new SchemaAxisButton(1, 0.3),
            undefined,
            undefined,
            new SchemaAxisButton(-3, 0.3),
            new SchemaAxisButton(3, 0.2),
            5,6,9,11
    )),
    new GameInputModel(
        GameInputSchemaType.Ragdoll,
        "joystick",
        "046d-c215-Logitech Logitech Extreme 3D Pro",
        "Linux",
        new GamepadAPI(undefined,
            new SchemaAxisButton(-6, 0.3),
            new SchemaAxisButton(6, 0.3),
            new SchemaAxisButton(-5, 0.3),
            new SchemaAxisButton(5, 0.3),
            12,
            1,2,3,4,
            new SchemaAxisButton(-2, 0.3),
            new SchemaAxisButton(2, 0.3),
            new SchemaAxisButton(-1, 0.3),
            new SchemaAxisButton(1, 0.3),
            undefined,
            undefined,
            new SchemaAxisButton(-3, 0.3),
            new SchemaAxisButton(3, 0.2),
            5,6,9,11
    )),
    new GameInputModel(
        GameInputSchemaType.Hedgehog,
        "generic",
        "Microsoft® Microsoft® SideWinder® Game Pad USB (Vendor: 045e Product: 0007)",
        "Linux",
        new GamepadAPI(undefined,
    /* d_up */  new SchemaAxisButton(-2),
    /* d_down */  new SchemaAxisButton(2),
    /* d_left */  new SchemaAxisButton(-1),
    /* d_right */  new SchemaAxisButton(1),
    /* menu */  10,
    /* button0 */  1,
    /* button1 */  2,
    /* button2 */  4,
    /* button3 */  5,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
    /* l_button */  6,
    /* r_button */  3,
    /* l_trigger */  7,
    /* r_trigger */  8
    )),
    new GameInputModel(
        GameInputSchemaType.Hedgehog,
        "generic",
        "045e-0007-Microsoft® Microsoft® SideWinder® Game Pad USB",
        "Linux",
        new GamepadAPI(undefined,
    /* d_up */  new SchemaAxisButton(-2),
    /* d_down */  new SchemaAxisButton(2),
    /* d_left */  new SchemaAxisButton(-1),
    /* d_right */  new SchemaAxisButton(1),
    /* menu */  10,
    /* button0 */  1,
    /* button1 */  2,
    /* button2 */  4,
    /* button3 */  5,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
    /* l_button */  6,
    /* r_button */  3,
    /* l_trigger */  7,
    /* r_trigger */  8
    )),
    new GameInputModel(
        GameInputSchemaType.Hedgehog,
        "generic",
        "ASUS Gamepad",
        "Android",
        new GamepadAPI(undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            12,
            1,2,3,4,
            new SchemaAxisButton(-2),
            new SchemaAxisButton(2),
            new SchemaAxisButton(-1),
            new SchemaAxisButton(1),
            new SchemaAxisButton(-4),
            new SchemaAxisButton(4),
            new SchemaAxisButton(-3),
            new SchemaAxisButton(3),
            7, 8, 5, 6
    )),
    new GameInputModel(
        GameInputSchemaType.Hedgehog,
        "generic",
        "NYKO PLAYPAD PRO",
        "Android",
        new GamepadAPI(undefined,
            new SchemaAxisButton(-8),
            new SchemaAxisButton(8),
            new SchemaAxisButton(-7),
            new SchemaAxisButton(7),
            10,
            2,3,1,4,
            new SchemaAxisButton(-2),
            new SchemaAxisButton(2),
            new SchemaAxisButton(-1),
            new SchemaAxisButton(1),
            new SchemaAxisButton(-6),
            new SchemaAxisButton(6),
            new SchemaAxisButton(-3),
            new SchemaAxisButton(3),
            5, 6, 7, 8
    )),
    new GameInputModel(
        GameInputSchemaType.Hedgehog,
        "generic",
        "Moga 2 HID",
        "Android",
        new GamepadAPI(undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            10,
            1, 2, 3, 4,
            new SchemaAxisButton(-2),
            new SchemaAxisButton(2),
            new SchemaAxisButton(-1),
            new SchemaAxisButton(1),
            undefined,
            undefined,
            undefined,
            undefined,
            7, 8,
            undefined,
            undefined
    )),
    new GameInputModel(
        GameInputSchemaType.Hedgehog,
        "generic",
        "Moga 2 HID (Vendor: 20d6 Product: 89e5)",
        "Linux",
        new GamepadAPI(undefined,
            new SchemaAxisButton(-8),
            new SchemaAxisButton(8),
            new SchemaAxisButton(-7),
            new SchemaAxisButton(7),
            7,
            1, 2, 3, 4,
            new SchemaAxisButton(-2),
            new SchemaAxisButton(2),
            new SchemaAxisButton(-1),
            new SchemaAxisButton(1),
            new SchemaAxisButton(-4),
            new SchemaAxisButton(4),
            new SchemaAxisButton(-3),
            new SchemaAxisButton(3),
            5, 6,
            new SchemaAxisButton(6),
            new SchemaAxisButton(5)
    )),
    new GameInputModel(
        GameInputSchemaType.Plumber,
        "nintendo-generic",
        "(null) usb gamepad            (Vendor: 0810 Product: e501)",
        "Linux",
        new GamepadAPI(undefined,
            /* d_up */  new SchemaAxisButton(-2),
            /* d_down */  new SchemaAxisButton(2),
            /* d_left */  new SchemaAxisButton(-1),
            /* d_right */  new SchemaAxisButton(1),
            /* menu */  10,
            /* button0 */  2,
            /* button1 */  3,
            /* button2 */  1,
            /* button3 */  4,
            /* l_up */  undefined,
            /* l_down */  undefined,
            /* l_left */  undefined,
            /* l_right */  undefined,
            /* r_up */  undefined,
            /* r_down */  undefined,
            /* r_left */  undefined,
            /* r_right */  undefined,
            /* l_button */  5,
            /* r_button */  6,
            /* l_trigger */  undefined,
            /* r_trigger */  undefined
    )),
    new GameInputModel(
    GameInputSchemaType.Plumber,
        "nintendo-generic",
        "0810-e501-usb gamepad           ",
        "Linux",
        new GamepadAPI(undefined,
            /* d_up */  new SchemaAxisButton(-2),
            /* d_down */  new SchemaAxisButton(2),
            /* d_left */  new SchemaAxisButton(-1),
            /* d_right */  new SchemaAxisButton(1),
            /* menu */  10,
            /* button0 */  2,
            /* button1 */  3,
            /* button2 */  1,
            /* button3 */  4,
            /* l_up */  undefined,
            /* l_down */  undefined,
            /* l_left */  undefined,
            /* l_right */  undefined,
            /* r_up */  undefined,
            /* r_down */  undefined,
            /* r_left */  undefined,
            /* r_right */  undefined,
            /* l_button */  5,
            /* r_button */  6,
            /* l_trigger */  undefined,
            /* r_trigger */  undefined
    )),
    new GameInputModel(
        GameInputSchemaType.Plumber,
        "nintendo-generic",
        "usb gamepad            (Vendor: 0810 Product: e501)",
        "macOS",
        new GamepadAPI(undefined,
            /* d_up */  new SchemaAxisButton(-2),
            /* d_down */  new SchemaAxisButton(2),
            /* d_left */  new SchemaAxisButton(-1),
            /* d_right */  new SchemaAxisButton(1),
            /* menu */  10,
            /* button0 */  2,
            /* button1 */  3,
            /* button2 */  1,
            /* button3 */  4,
            /* l_up */  undefined,
            /* l_down */  undefined,
            /* l_left */  undefined,
            /* l_right */  undefined,
            /* r_up */  undefined,
            /* r_down */  undefined,
            /* r_left */  undefined,
            /* r_right */  undefined,
            /* l_button */  5,
            /* r_button */  6,
            /* l_trigger */  undefined,
            /* r_trigger */  undefined
    )),
    new GameInputModel(
    GameInputSchemaType.Plumber,
        "nintendo-generic",
        "810-e501-usb gamepad           ",
        "macOS",
        new GamepadAPI(undefined,
            /* d_up */  new SchemaAxisButton(-3),
            /* d_down */  new SchemaAxisButton(3),
            /* d_left */  new SchemaAxisButton(-2),
            /* d_right */  new SchemaAxisButton(2),
            /* menu */  10,
            /* button0 */  2,
            /* button1 */  3,
            /* button2 */  1,
            /* button3 */  4,
            /* l_up */  undefined,
            /* l_down */  undefined,
            /* l_left */  undefined,
            /* l_right */  undefined,
            /* r_up */  undefined,
            /* r_down */  undefined,
            /* r_left */  undefined,
            /* r_right */  undefined,
            /* l_button */  5,
            /* r_button */  6,
            /* l_trigger */  undefined,
            /* r_trigger */  undefined
    )),
    new GameInputModel(
        GameInputSchemaType.Hedgehog,
        "generic",
        "Gravis GamePad Pro USB  (Vendor: 0428 Product: 4001)",
        "Linux",
        GravisGamepadProSchema),
    new GameInputModel(
        GameInputSchemaType.Hedgehog,
        "generic",
        "0428-4001-Gravis GamePad Pro USB ",
        "Linux",
        GravisGamepadProSchema),
    new GameInputModel(
        GameInputSchemaType.Hedgehog,
        "generic",
        "GamePad Pro USB  (Vendor: 0428 Product: 4001)",
        "macOS",
        GravisGamepadProSchema),
    new GameInputModel(
        GameInputSchemaType.Hedgehog,
        "generic",
        "428-4001-GamePad Pro USB ",
        "macOS",
        GravisGamepadProSchema),
    new GameInputModel(
        GameInputSchemaType.Hedgehog,
        "xboxone",
        "Performance Designed Products Afterglow Wired Controller for Xbox One (Vendor: 0e6f Product: 0139)",
        "Linux",
        new GamepadAPI(undefined,
            /* d_up */  new SchemaAxisButton(-8),
            /* d_down */  new SchemaAxisButton(8),
            /* d_left */  new SchemaAxisButton(-7),
            /* d_right */  new SchemaAxisButton(7),
            /* menu */  8,
            /* button0 */  1,
            /* button1 */  2,
            /* button2 */  3,
            /* button3 */  4,
            /* l_up */  new SchemaAxisButton(-2),
            /* l_down */  new SchemaAxisButton(2),
            /* l_left */  new SchemaAxisButton(-1),
            /* l_right */  new SchemaAxisButton(1),
            /* r_up */  new SchemaAxisButton(-5),
            /* r_down */  new SchemaAxisButton(5),
            /* r_left */  new SchemaAxisButton(-4),
            /* r_right */  new SchemaAxisButton(4),
            /* l_button */  5,
            /* r_button */  6,
            /* l_trigger */  new SchemaAxisButton(3),
            /* r_trigger */  new SchemaAxisButton(6)
        )),
    new GameInputModel(
        GameInputSchemaType.Hedgehog,
        "xboxone",
        "0e6f-0139-Afterglow Prismatic Wired Controller",
        "Linux",
        new GamepadAPI(undefined,
            /* d_up */  new SchemaAxisButton(-8),
            /* d_down */  new SchemaAxisButton(8),
            /* d_left */  new SchemaAxisButton(-7),
            /* d_right */  new SchemaAxisButton(7),
            /* menu */  8,
            /* button0 */  1,
            /* button1 */  2,
            /* button2 */  3,
            /* button3 */  4,
            /* l_up */  new SchemaAxisButton(-2),
            /* l_down */  new SchemaAxisButton(2),
            /* l_left */  new SchemaAxisButton(-1),
            /* l_right */  new SchemaAxisButton(1),
            /* r_up */  new SchemaAxisButton(-5),
            /* r_down */  new SchemaAxisButton(5),
            /* r_left */  new SchemaAxisButton(-4),
            /* r_right */  new SchemaAxisButton(4),
            /* l_button */  5,
            /* r_button */  6,
            /* l_trigger */  new SchemaAxisButton(3),
            /* r_trigger */  new SchemaAxisButton(6)
        )),
    new GameInputModel(
        GameInputSchemaType.Plumber,
        "nintendo-generic",
        "USB,2-axis 8-button gamepad   (STANDARD GAMEPAD Vendor: 0583 Product: 2060)",
        "macOS",
        new GamepadAPI(undefined,
            /* d_up */  13,
            /* d_down */  14,
            /* d_left */  15,
            /* d_right */  16,
            /* menu */  10,
            /* button0 */  2,
            /* button1 */  1,
            /* button2 */  4,
            /* button3 */  3,
            /* l_up */  undefined,
            /* l_down */  undefined,
            /* l_left */  undefined,
            /* l_right */  undefined,
            /* r_up */  undefined,
            /* r_down */  undefined,
            /* r_left */  undefined,
            /* r_right */  undefined,
            /* l_button */  5,
            /* r_button */  6,
            /* l_trigger */  undefined,
            /* r_trigger */  undefined
        )),
    new GameInputModel(
        GameInputSchemaType.Plumber,
        "nintendo-generic",
        "0583-2060-USB,2-axis 8-button gamepad   ",
        "macOS",
        new GamepadAPI(undefined,
            /* d_up */  13,
            /* d_down */  14,
            /* d_left */  15,
            /* d_right */  16,
            /* menu */  10,
            /* button0 */  2,
            /* button1 */  1,
            /* button2 */  4,
            /* button3 */  3,
            /* l_up */  undefined,
            /* l_down */  undefined,
            /* l_left */  undefined,
            /* l_right */  undefined,
            /* r_up */  undefined,
            /* r_down */  undefined,
            /* r_left */  undefined,
            /* r_right */  undefined,
            /* l_button */  5,
            /* r_button */  6,
            /* l_trigger */  undefined,
            /* r_trigger */  undefined
        )),
    new GameInputModel(
        GameInputSchemaType.Plumber, // it's a square and x /y are generic style, while a / b are nintendo style - FAMICOM
        "nintendo-generic",
        "BUFFALO BGC-FC801 USB Gamepad (Vendor: 0411 Product: 00c6)",
        "macOS",
        new GamepadAPI(undefined,
            /* d_up */  new SchemaAxisButton(-2),
            /* d_down */  new SchemaAxisButton(2),
            /* d_left */  new SchemaAxisButton(-1),
            /* d_right */  new SchemaAxisButton(1),
            /* menu */  8,
            /* button0 */  1,
            /* button1 */  2,
            /* button2 */  3,
            /* button3 */  4,
            /* l_up */  undefined,
            /* l_down */  undefined,
            /* l_left */  undefined,
            /* l_right */  undefined,
            /* r_up */  undefined,
            /* r_down */  undefined,
            /* r_left */  undefined,
            /* r_right */  undefined,
            /* l_button */  5,
            /* r_button */  6,
            /* l_trigger */  undefined,
            /* r_trigger */  undefined
        )),
    new GameInputModel(
        GameInputSchemaType.Plumber, // it's a square and x /y are generic style, while a / b are nintendo style - FAMICOM
        "nintendo-generic",
        "0411-00c6-BUFFALO BGC-FC801 USB Gamepad ",
        "macOS",
        new GamepadAPI(undefined,
            /* d_up */  new SchemaAxisButton(-2),
            /* d_down */  new SchemaAxisButton(2),
            /* d_left */  new SchemaAxisButton(-1),
            /* d_right */  new SchemaAxisButton(1),
            /* menu */  8,
            /* button0 */  1,
            /* button1 */  2,
            /* button2 */  3,
            /* button3 */  4,
            /* l_up */  undefined,
            /* l_down */  undefined,
            /* l_left */  undefined,
            /* l_right */  undefined,
            /* r_up */  undefined,
            /* r_down */  undefined,
            /* r_left */  undefined,
            /* r_right */  undefined,
            /* l_button */  5,
            /* r_button */  6,
            /* l_trigger */  undefined,
            /* r_trigger */  undefined
        )),
    new GameInputModel(
        GameInputSchemaType.Hedgehog, // should be numbers, see issue #16
        "generic",
        "USB  Joystick (Vendor: 1345 Product: 1030)",
        "macOS",
        new GamepadAPI(undefined,
            /* d_up */  new SchemaAxisButton(-2),
            /* d_down */  new SchemaAxisButton(2),
            /* d_left */  new SchemaAxisButton(-1),
            /* d_right */  new SchemaAxisButton(1),
            /* menu */  10,
            /* button0 */  3,
            /* button1 */  2,
            /* button2 */  4,
            /* button3 */  1,
            /* l_up */  undefined,
            /* l_down */  undefined,
            /* l_left */  undefined,
            /* l_right */  undefined,
            /* r_up */  undefined,
            /* r_down */  undefined,
            /* r_left */  undefined,
            /* r_right */  undefined,
            /* l_button */  5,
            /* r_button */  6,
            /* l_trigger */  7,
            /* r_trigger */  8
        )),
    new GameInputModel(
        GameInputSchemaType.Hedgehog, // should be numbers, see issue #16
        "generic",
        "1345-1030-USB  Joystick ",
        "macOS",
        new GamepadAPI(undefined,
            /* d_up */  new SchemaAxisButton(-2),
            /* d_down */  new SchemaAxisButton(2),
            /* d_left */  new SchemaAxisButton(-1),
            /* d_right */  new SchemaAxisButton(1),
            /* menu */  10,
            /* button0 */  3,
            /* button1 */  2,
            /* button2 */  4,
            /* button3 */  1,
            /* l_up */  undefined,
            /* l_down */  undefined,
            /* l_left */  undefined,
            /* l_right */  undefined,
            /* r_up */  undefined,
            /* r_down */  undefined,
            /* r_left */  undefined,
            /* r_right */  undefined,
            /* l_button */  5,
            /* r_button */  6,
            /* l_trigger */  7,
            /* r_trigger */  8
        )),
    new GameInputModel(
        GameInputSchemaType.Hedgehog,
        "joystick",
        "Innovative Produtcs VR Pro 2000 USB Joystick (Vendor: 04b4 Product: 2774)",
        "Linux",
        new GamepadAPI(undefined,
            /* d_up */  13,
            /* d_down */  14,
            /* d_left */  15,
            /* d_right */  16,
            /* menu */  4,
            /* button0 */  1,
            /* button1 */  2,
            /* button2 */  3,
            /* button3 */  new SchemaAxisButton(-3, frenchVRStickThreshold, frenchVRStickDeadzone),
            /* l_up */  new SchemaAxisButton(2, frenchVRStickThreshold, frenchVRStickDeadzone),
            /* l_down */  new SchemaAxisButton(-2, frenchVRStickThreshold, frenchVRStickDeadzone),
            /* l_left */  new SchemaAxisButton(1, frenchVRStickThreshold, frenchVRStickDeadzone),
            /* l_right */  new SchemaAxisButton(-1, frenchVRStickThreshold, frenchVRStickDeadzone),
            /* r_up */  new SchemaAxisButton(-6, frenchVRStickThreshold, frenchVRStickDeadzone),
            /* r_down */  new SchemaAxisButton(6, frenchVRStickThreshold, frenchVRStickDeadzone),
            /* r_left */  new SchemaAxisButton(-5, frenchVRStickThreshold, frenchVRStickDeadzone),
            /* r_right */  new SchemaAxisButton(5, frenchVRStickThreshold, frenchVRStickDeadzone),
            /* l_button */  5,
            /* r_button */  6,
            /* l_trigger */  7,
            /* r_trigger */  8
        )),
    new GameInputModel(
        GameInputSchemaType.Hedgehog,
        "joystick",
        "04b4-2774-Innovative Produtcs VR Pro 2000 USB Joystick",
        "Linux",
        new GamepadAPI(undefined,
            /* d_up */  13,
            /* d_down */  14,
            /* d_left */  15,
            /* d_right */  16,
            /* menu */  4,
            /* button0 */  1,
            /* button1 */  2,
            /* button2 */  3,
            /* button3 */  new SchemaAxisButton(-3, frenchVRStickThreshold, frenchVRStickDeadzone),
            /* l_up */  new SchemaAxisButton(2, frenchVRStickThreshold, frenchVRStickDeadzone),
            /* l_down */  new SchemaAxisButton(-2, frenchVRStickThreshold, frenchVRStickDeadzone),
            /* l_left */  new SchemaAxisButton(1, frenchVRStickThreshold, frenchVRStickDeadzone),
            /* l_right */  new SchemaAxisButton(-1, frenchVRStickThreshold, frenchVRStickDeadzone),
            /* r_up */  new SchemaAxisButton(-6, frenchVRStickThreshold, frenchVRStickDeadzone),
            /* r_down */  new SchemaAxisButton(6, frenchVRStickThreshold, frenchVRStickDeadzone),
            /* r_left */  new SchemaAxisButton(-5, frenchVRStickThreshold, frenchVRStickDeadzone),
            /* r_right */  new SchemaAxisButton(5, frenchVRStickThreshold, frenchVRStickDeadzone),
            /* l_button */  5,
            /* r_button */  6,
            /* l_trigger */  7,
            /* r_trigger */  8
        )),
    new GameInputModel(
        GameInputSchemaType.Plumber,
        "nintendo-generic",
        "20d6-a711-Bensussen Deutsch & Associates,Inc.(BDA) Core (Plus) Wired Controller",
        "Linux",
        new GamepadAPI(undefined,
            /* d_up */  new SchemaAxisButton(-6),
            /* d_down */  new SchemaAxisButton(6),
            /* d_left */  new SchemaAxisButton(-5),
            /* d_right */  new SchemaAxisButton(5),
            /* menu */  10,
            /* button0 */  3,
            /* button1 */  2,
            /* button2 */  4,
            /* button3 */  1,
            /* l_up */  new SchemaAxisButton(-2),
            /* l_down */  new SchemaAxisButton(2),
            /* l_left */  new SchemaAxisButton(-1),
            /* l_right */  new SchemaAxisButton(1),
            /* r_up */  new SchemaAxisButton(-4),
            /* r_down */  new SchemaAxisButton(4),
            /* r_left */  new SchemaAxisButton(-3),
            /* r_right */  new SchemaAxisButton(3),
            /* l_button */  5,
            /* r_button */  6,
            /* l_trigger */  7,
            /* r_trigger */  8
        )
    ),
    new GameInputModel(
        GameInputSchemaType.Plumber,
        "nintendo-generic",
        "Bensussen Deutsch & Associates,Inc.(BDA) Core (Plus) Wired Controller (Vendor: 20d6 Product: a711)",
        "Linux",
        new GamepadAPI(undefined,
            /* d_up */  new SchemaAxisButton(-6),
            /* d_down */  new SchemaAxisButton(6),
            /* d_left */  new SchemaAxisButton(-5),
            /* d_right */  new SchemaAxisButton(5),
            /* menu */  10,
            /* button0 */  3,
            /* button1 */  2,
            /* button2 */  4,
            /* button3 */  1,
            /* l_up */  new SchemaAxisButton(-2),
            /* l_down */  new SchemaAxisButton(2),
            /* l_left */  new SchemaAxisButton(-1),
            /* l_right */  new SchemaAxisButton(1),
            /* r_up */  new SchemaAxisButton(-4),
            /* r_down */  new SchemaAxisButton(4),
            /* r_left */  new SchemaAxisButton(-3),
            /* r_right */  new SchemaAxisButton(3),
            /* l_button */  5,
            /* r_button */  6,
            /* l_trigger */  7,
            /* r_trigger */  8
        )
    ),
];


export default GameInputModels
export {GameInputModels, GravisGamepadProSchema}
/**
 * @preserve
 * @license-end
 */
