import { GameInputModel } from './gameinput-model.js'
import { GameInputSchema } from './gameinput-schema.js'
import { GamepadMapping } from './gamepad-mapping.js'
import { AxisAsButton } from './axis-as-button.js'

const frenchVRStickDeadzone = 0.6
const frenchVRStickThreshold = 0.8

const GravisGamepadProSchema = new GamepadMapping(
    /* dpadUp */ new AxisAsButton(-2),
    /* dpadDown */ new AxisAsButton(2),
    /* dpadLeft */ new AxisAsButton(-1),
    /* dpadRight */ new AxisAsButton(1),
    /* menu */ 10,
    /* button0 */ 2,
    /* button1 */ 3,
    /* button2 */ 1,
    /* button3 */ 4,
    /* leftStickUp */ undefined,
    /* leftStickDown */ undefined,
    /* leftStickLeft */ undefined,
    /* leftStickRight */ undefined,
    /* rightStickUp */ new AxisAsButton(-4),
    /* rightStickDown */ new AxisAsButton(4),
    /* rightStickLeft */ new AxisAsButton(-3),
    /* rightStickRight */ new AxisAsButton(3),
    /* leftShoulder */ 5,
    /* rightShoulder */ 6,
    /* leftTrigger */ 7,
    /* rightTrigger */ 8
)

/*
    * "HuiJia  PS/SS/N64 Joypad to USB BOX (Vendor: 0925 Product: 1700)"
    * Force to manually configure this multiple-configuration adapter instead of assuming which adapter port you're using
    */

const GameInputModels = [
    new GameInputModel(
        GameInputSchema.Hedgehog,
        'xbox360',
        'Xbox 360 Controller (XInput STANDARD GAMEPAD)',
        'Windows'
    ),
    new GameInputModel(
        GameInputSchema.Plumber,
        'nintendo-generic',
        '0925-8866-SFC/USB Pad',
        'Windows',
        new GamepadMapping(
            new AxisAsButton(-2),
            new AxisAsButton(2),
            new AxisAsButton(-1),
            new AxisAsButton(1),
            8,
            2, 1, 4, 3,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            5, 6, undefined, undefined
        )),
    new GameInputModel(
        GameInputSchema.Plumber,
        'nintendo-generic',
        'SFC/USB Pad (Vendor: 0925 Product: 8866)',
        'Windows',
        new GamepadMapping(
            new AxisAsButton(-2),
            new AxisAsButton(2),
            new AxisAsButton(-1),
            new AxisAsButton(1),
            8,
            2, 1, 4, 3,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            5, 6, undefined, undefined
        )),
    new GameInputModel(
        GameInputSchema.Hedgehog,
        'xbox360',
        'Xbox 360 Wireless Receiver (Vendor: 0000 Product: 0000)',
        'Linux',
        new GamepadMapping(
            16, 17, 14, 15,
            10,
            2, 1, 4, 3,
            new AxisAsButton(-2),
            new AxisAsButton(2),
            new AxisAsButton(-1),
            new AxisAsButton(1),
            new AxisAsButton(-4),
            new AxisAsButton(4),
            new AxisAsButton(-3),
            new AxisAsButton(3),
            5, 6, 7, 8
        )),
    new GameInputModel(
        GameInputSchema.Hedgehog,
        'xbox360',
        '0000-0000-Xbox 360 Wireless Receiver',
        'Linux',
        new GamepadMapping(
            16, 17, 14, 15,
            10,
            1, 2, 3, 4,
            new AxisAsButton(-2),
            new AxisAsButton(2),
            new AxisAsButton(-1),
            new AxisAsButton(1),
            new AxisAsButton(-4),
            new AxisAsButton(4),
            new AxisAsButton(-3),
            new AxisAsButton(3),
            5, 6, 7, 8
        )),
    new GameInputModel(
        GameInputSchema.Ragdoll,
        'ds4',
        'Wireless Controller (STANDARD GAMEPAD Vendor: 054c Product: 05c4)',
        'Windows'
    ),
    new GameInputModel(
        GameInputSchema.Ragdoll,
        'ds4',
        'Wireless Controller (STANDARD GAMEPAD Vendor: 054c Product: 05c4)',
        'macOS'
    ),
    new GameInputModel(
        GameInputSchema.Ragdoll,
        'ds4',
        '054c-05c4-Wireless Controller',
        'Windows',
        new GamepadMapping(
            15, 16, 17, 18,
            10,
            2, 3, 1, 4,
            new AxisAsButton(-2),
            new AxisAsButton(2),
            new AxisAsButton(-1),
            new AxisAsButton(1),
            new AxisAsButton(-6),
            new AxisAsButton(6),
            new AxisAsButton(-3),
            new AxisAsButton(3),
            5, 6, 7, 8
        )),
    new GameInputModel(
        GameInputSchema.Hedgehog,
        'xbox360',
        '©Microsoft Corporation Controller (STANDARD GAMEPAD Vendor: 045e Product: 028e)',
        'Linux'
    ),
    new GameInputModel(
        GameInputSchema.Hedgehog,
        'xbox360',
        'Performance Designed Products Afterglow Gamepad for Xbox 360 (STANDARD GAMEPAD Vendor: 0e6f Product: 0213)',
        'Linux'
    ),
    new GameInputModel(
        GameInputSchema.Hedgehog,
        'xbox360',
        'Performance Designed Products Afterglow Gamepad for Xbox 360 (Vendor: 0e6f Product: 0213)',
        'Linux',
        new GamepadMapping(
            new AxisAsButton(-8),
            new AxisAsButton(8),
            new AxisAsButton(-7),
            new AxisAsButton(7),
            8,
            1, 2, 3, 4,
            new AxisAsButton(-2),
            new AxisAsButton(2),
            new AxisAsButton(-1),
            new AxisAsButton(1),
            new AxisAsButton(-5),
            new AxisAsButton(5),
            new AxisAsButton(-4),
            new AxisAsButton(4),
            5,
            6,
            new AxisAsButton(3),
            new AxisAsButton(6)
        )),
    new GameInputModel(
        GameInputSchema.Hedgehog,
        'xbox360',
        '0e6f-0213-Afterglow Gamepad for Xbox 360',
        'Linux',
        new GamepadMapping(
            new AxisAsButton(-8),
            new AxisAsButton(8),
            new AxisAsButton(-7),
            new AxisAsButton(7),
            8,
            1, 2, 3, 4,
            new AxisAsButton(-2),
            new AxisAsButton(2),
            new AxisAsButton(-1),
            new AxisAsButton(1),
            new AxisAsButton(-5),
            new AxisAsButton(5),
            new AxisAsButton(-4),
            new AxisAsButton(4),
            5,
            6,
            new AxisAsButton(3),
            new AxisAsButton(6)
        )),
    new GameInputModel(
        GameInputSchema.Hedgehog,
        'dc',
        'HuiJia  USB GamePad (Vendor: 0e8f Product: 3013)',
        'Linux',
        new GamepadMapping(
            13, 15, 16, 14,
            10,
            1, 2, 3, 4,
            new AxisAsButton(-2),
            new AxisAsButton(2),
            new AxisAsButton(-1),
            new AxisAsButton(1),
            undefined,
            undefined,
            undefined,
            undefined,
            undefined, undefined, 5, 6
        )),
    new GameInputModel(
        GameInputSchema.Hedgehog,
        'dc',
        'USB GamePad (Vendor: 0e8f Product: 3013)',
        'Windows',
        new GamepadMapping(
            13, 15, 16, 14,
            10,
            1, 2, 3, 4,
            new AxisAsButton(-2),
            new AxisAsButton(2),
            new AxisAsButton(-1),
            new AxisAsButton(1),
            undefined,
            undefined,
            undefined,
            undefined,
            undefined, undefined, 5, 6
        )),
    new GameInputModel(
        GameInputSchema.Hedgehog,
        'dc',
        'USB GamePad (Vendor: 0e8f Product: 3013)',
        'macOS',
        new GamepadMapping(
            13, 15, 16, 14,
            10,
            1, 2, 3, 4,
            new AxisAsButton(-2),
            new AxisAsButton(2),
            new AxisAsButton(-1),
            new AxisAsButton(1),
            undefined,
            undefined,
            undefined,
            undefined,
            undefined, undefined, 5, 6
        )),
    new GameInputModel(
        GameInputSchema.RagdollOld,
        'ds3',
        'Sony PLAYSTATION(R)3 Controller (STANDARD GAMEPAD Vendor: 054c Product: 0268)',
        'Linux'
    ),
    new GameInputModel(
        GameInputSchema.RagdollOld,
        'ds3',
        '054c-0268-Sony PLAYSTATION(R)3 Controller',
        'Linux',
        new GamepadMapping(
            5, 7, 8, 6,
            4,
            15, 14, 16, 13,
            new AxisAsButton(-2),
            new AxisAsButton(2),
            new AxisAsButton(-1),
            new AxisAsButton(1),
            new AxisAsButton(-4),
            new AxisAsButton(4),
            new AxisAsButton(-3),
            new AxisAsButton(3),
            11, 12, 9, 10
        )),
    new GameInputModel(
        GameInputSchema.Ragdoll,
        'ds4',
        'Sony Computer Entertainment Wireless Controller (STANDARD GAMEPAD Vendor: 054c Product: 05c4)',
        'Linux'
    ),
    new GameInputModel(
        GameInputSchema.Ragdoll,
        'ds4',
        '054c-05c4-Sony Computer Entertainment Wireless Controller',
        'Linux',
        new GamepadMapping(
            new AxisAsButton(-8),
            new AxisAsButton(8),
            new AxisAsButton(-7),
            new AxisAsButton(7),
            10,
            2, 3, 1, 4,
            new AxisAsButton(-2),
            new AxisAsButton(2),
            new AxisAsButton(-1),
            new AxisAsButton(1),
            new AxisAsButton(-6),
            new AxisAsButton(6),
            new AxisAsButton(-3),
            new AxisAsButton(3),
            5, 6, 7, 8
        )),
    new GameInputModel(
        GameInputSchema.Hedgehog,
        'joystick',
        'Mayflash Arcade Stick (Vendor: 0e8f Product: 0003)',
        'Windows',
        new GamepadMapping(
            new AxisAsButton(-2),
            new AxisAsButton(2),
            new AxisAsButton(-1),
            new AxisAsButton(1),
            10,
            1, 2, 3, 4,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            5, 6, 7, 8
        )),
    new GameInputModel(
        GameInputSchema.Hedgehog,
        'joystick',
        'PLAYSTATION(R)3 Controller (STANDARD GAMEPAD Vendor: 054c Product: 0268)', /* Mayflash Arcade Stick */
        'macOS',
        new GamepadMapping(
            13, 14, 15, 16,
            10,
            7, 1, 2, 8,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            5, 3, 4, 6
        )),
    new GameInputModel(
        GameInputSchema.RagdollOld,
        'joystick',
        'MY-POWER CO.,LTD. Mayflash Arcade Stick (STANDARD GAMEPAD Vendor: 0e8f Product: 0003)',
        'Linux',
        new GamepadMapping(
            new AxisAsButton(-3),
            new AxisAsButton(3),
            new AxisAsButton(-4),
            new AxisAsButton(4),
            10,
            4, 2, 1, 3,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            7, 8, 5, 6
        )),
    new GameInputModel(
        GameInputSchema.RagdollOld,
        'joystick',
        '0e8f-0003-MY-POWER CO.,LTD. Mayflash Arcade Stick',
        'Linux',
        new GamepadMapping(
            new AxisAsButton(-2),
            new AxisAsButton(2),
            new AxisAsButton(-1),
            new AxisAsButton(1),
            10,
            1, 2, 3, 4,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            5, 6, 7, 8
        )),
    new GameInputModel(
        GameInputSchema.Hedgehog,
        'generic',
        'Logitech Logitech Dual Action (Vendor: 046d Product: c216)', // DirectInput (XInput uses 'standard' mapping)
        'Linux',
        new GamepadMapping(
            /* dpadUp */ new AxisAsButton(-6),
            /* dpadDown */ new AxisAsButton(6),
            /* dpadLeft */ new AxisAsButton(-5),
            /* dpadRight */ new AxisAsButton(5),
            /* menu */ 10,
            /* button0 */ 2,
            /* button1 */ 3,
            /* button2 */ 1,
            /* button3 */ 4,
            /* leftStickUp */ new AxisAsButton(-2),
            /* leftStickDown */ new AxisAsButton(2),
            /* leftStickLeft */ new AxisAsButton(-1),
            /* leftStickRight */ new AxisAsButton(1),
            /* rightStickUp */ new AxisAsButton(-4),
            /* rightStickDown */ new AxisAsButton(4),
            /* rightStickLeft */ new AxisAsButton(-3),
            /* rightStickRight */ new AxisAsButton(3),
            /* leftShoulder */ 5,
            /* rightShoulder */ 6,
            /* leftTrigger */ 7,
            /* rightTrigger */ 8
        )),
    new GameInputModel(
        GameInputSchema.Hedgehog,
        'generic',
        'Logitech Gamepad F310 (Vendor: 046d Product: c21d)',
        'Linux',
        new GamepadMapping(
            /* dpadUp */ new AxisAsButton(-8),
            /* dpadDown */ new AxisAsButton(8),
            /* dpadLeft */ new AxisAsButton(-7),
            /* dpadRight */ new AxisAsButton(7),
            /* menu */ 8,
            /* button0 */ 1,
            /* button1 */ 2,
            /* button2 */ 3,
            /* button3 */ 4,
            /* leftStickUp */ new AxisAsButton(-2),
            /* leftStickDown */ new AxisAsButton(2),
            /* leftStickLeft */ new AxisAsButton(-1),
            /* leftStickRight */ new AxisAsButton(1),
            /* rightStickUp */ new AxisAsButton(-5),
            /* rightStickDown */ new AxisAsButton(5),
            /* rightStickLeft */ new AxisAsButton(-4),
            /* rightStickRight */ new AxisAsButton(4),
            /* leftShoulder */ 5,
            /* rightShoulder */ 6,
            /* leftTrigger */ new AxisAsButton(3),
            /* rightTrigger */ new AxisAsButton(6)
        )),
    new GameInputModel(
        GameInputSchema.Hedgehog,
        'generic',
        '046d-c21d-Logitech Gamepad F310', // XInput
        'Linux',
        new GamepadMapping(
            /* dpadUp */ new AxisAsButton(-8),
            /* dpadDown */ new AxisAsButton(8),
            /* dpadLeft */ new AxisAsButton(-7),
            /* dpadRight */ new AxisAsButton(7),
            /* menu */ 8,
            /* button0 */ 1,
            /* button1 */ 2,
            /* button2 */ 3,
            /* button3 */ 4,
            /* leftStickUp */ new AxisAsButton(-2),
            /* leftStickDown */ new AxisAsButton(2),
            /* leftStickLeft */ new AxisAsButton(-1),
            /* leftStickRight */ new AxisAsButton(1),
            /* rightStickUp */ new AxisAsButton(-5),
            /* rightStickDown */ new AxisAsButton(5),
            /* rightStickLeft */ new AxisAsButton(-4),
            /* rightStickRight */ new AxisAsButton(4),
            /* leftShoulder */ 5,
            /* rightShoulder */ 6,
            /* leftTrigger */ new AxisAsButton(3),
            /* rightTrigger */ new AxisAsButton(6)
        )),
    new GameInputModel(
        GameInputSchema.Hedgehog,
        'generic',
        '046d-c216-Logitech Logitech Dual Action', // DirectInput (XInput uses 'standard' mapping)
        'Linux',
        new GamepadMapping(
            /* dpadUp */ new AxisAsButton(-6),
            /* dpadDown */ new AxisAsButton(6),
            /* dpadLeft */ new AxisAsButton(-5),
            /* dpadRight */ new AxisAsButton(5),
            /* menu */ 10,
            /* button0 */ 2,
            /* button1 */ 3,
            /* button2 */ 1,
            /* button3 */ 4,
            /* leftStickUp */ new AxisAsButton(-2),
            /* leftStickDown */ new AxisAsButton(2),
            /* leftStickLeft */ new AxisAsButton(-1),
            /* leftStickRight */ new AxisAsButton(1),
            /* rightStickUp */ new AxisAsButton(-4),
            /* rightStickDown */ new AxisAsButton(4),
            /* rightStickLeft */ new AxisAsButton(-3),
            /* rightStickRight */ new AxisAsButton(3),
            /* leftShoulder */ 5,
            /* rightShoulder */ 6,
            /* leftTrigger */ 7,
            /* rightTrigger */ 8
        )),
    new GameInputModel(
        GameInputSchema.RagdollOld,
        'joystick',
        'Logitech Logitech Extreme 3D Pro (Vendor: 046d Product: c215)',
        'Linux',
        new GamepadMapping(
            new AxisAsButton(-6, 0.3),
            new AxisAsButton(6, 0.3),
            new AxisAsButton(-5, 0.3),
            new AxisAsButton(5, 0.3),
            12,
            1, 2, 3, 4,
            new AxisAsButton(-2, 0.3),
            new AxisAsButton(2, 0.3),
            new AxisAsButton(-1, 0.3),
            new AxisAsButton(1, 0.3),
            undefined,
            undefined,
            new AxisAsButton(-3, 0.3),
            new AxisAsButton(3, 0.2),
            5, 6, 9, 11
        )),
    new GameInputModel(
        GameInputSchema.RagdollOld,
        'joystick',
        '046d-c215-Logitech Logitech Extreme 3D Pro',
        'Linux',
        new GamepadMapping(
            new AxisAsButton(-6, 0.3),
            new AxisAsButton(6, 0.3),
            new AxisAsButton(-5, 0.3),
            new AxisAsButton(5, 0.3),
            12,
            1, 2, 3, 4,
            new AxisAsButton(-2, 0.3),
            new AxisAsButton(2, 0.3),
            new AxisAsButton(-1, 0.3),
            new AxisAsButton(1, 0.3),
            undefined,
            undefined,
            new AxisAsButton(-3, 0.3),
            new AxisAsButton(3, 0.2),
            5, 6, 9, 11
        )),
    new GameInputModel(
        GameInputSchema.Hedgehog,
        'generic',
        'Microsoft® Microsoft® SideWinder® Game Pad USB (Vendor: 045e Product: 0007)',
        'Linux',
        new GamepadMapping(
            /* dpadUp */ new AxisAsButton(-2),
            /* dpadDown */ new AxisAsButton(2),
            /* dpadLeft */ new AxisAsButton(-1),
            /* dpadRight */ new AxisAsButton(1),
            /* menu */ 10,
            /* button0 */ 1,
            /* button1 */ 2,
            /* button2 */ 4,
            /* button3 */ 5,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            /* leftShoulder */ 6,
            /* rightShoulder */ 3,
            /* leftTrigger */ 7,
            /* rightTrigger */ 8
        )),
    new GameInputModel(
        GameInputSchema.Hedgehog,
        'generic',
        '045e-0007-Microsoft® Microsoft® SideWinder® Game Pad USB',
        'Linux',
        new GamepadMapping(
            /* dpadUp */ new AxisAsButton(-2),
            /* dpadDown */ new AxisAsButton(2),
            /* dpadLeft */ new AxisAsButton(-1),
            /* dpadRight */ new AxisAsButton(1),
            /* menu */ 10,
            /* button0 */ 1,
            /* button1 */ 2,
            /* button2 */ 4,
            /* button3 */ 5,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            /* leftShoulder */ 6,
            /* rightShoulder */ 3,
            /* leftTrigger */ 7,
            /* rightTrigger */ 8
        )),
    new GameInputModel(
        GameInputSchema.Hedgehog,
        'generic',
        'ASUS Gamepad',
        'Android',
        new GamepadMapping(
            undefined,
            undefined,
            undefined,
            undefined,
            12,
            1, 2, 3, 4,
            new AxisAsButton(-2),
            new AxisAsButton(2),
            new AxisAsButton(-1),
            new AxisAsButton(1),
            new AxisAsButton(-4),
            new AxisAsButton(4),
            new AxisAsButton(-3),
            new AxisAsButton(3),
            7, 8, 5, 6
        )),
    new GameInputModel(
        GameInputSchema.Hedgehog,
        'generic',
        'NYKO PLAYPAD PRO',
        'Android',
        new GamepadMapping(
            new AxisAsButton(-8),
            new AxisAsButton(8),
            new AxisAsButton(-7),
            new AxisAsButton(7),
            10,
            2, 3, 1, 4,
            new AxisAsButton(-2),
            new AxisAsButton(2),
            new AxisAsButton(-1),
            new AxisAsButton(1),
            new AxisAsButton(-6),
            new AxisAsButton(6),
            new AxisAsButton(-3),
            new AxisAsButton(3),
            5, 6, 7, 8
        )),
    new GameInputModel(
        GameInputSchema.Hedgehog,
        'generic',
        'Moga 2 HID',
        'Android',
        new GamepadMapping(
            undefined,
            undefined,
            undefined,
            undefined,
            10,
            1, 2, 3, 4,
            new AxisAsButton(-2),
            new AxisAsButton(2),
            new AxisAsButton(-1),
            new AxisAsButton(1),
            undefined,
            undefined,
            undefined,
            undefined,
            7, 8,
            undefined,
            undefined
        )),
    new GameInputModel(
        GameInputSchema.Hedgehog,
        'generic',
        'Moga 2 HID (Vendor: 20d6 Product: 89e5)',
        'Linux',
        new GamepadMapping(
            new AxisAsButton(-8),
            new AxisAsButton(8),
            new AxisAsButton(-7),
            new AxisAsButton(7),
            7,
            1, 2, 3, 4,
            new AxisAsButton(-2),
            new AxisAsButton(2),
            new AxisAsButton(-1),
            new AxisAsButton(1),
            new AxisAsButton(-4),
            new AxisAsButton(4),
            new AxisAsButton(-3),
            new AxisAsButton(3),
            5, 6,
            new AxisAsButton(6),
            new AxisAsButton(5)
        )),
    new GameInputModel(
        GameInputSchema.Plumber,
        'nintendo-generic',
        '(null) usb gamepad            (Vendor: 0810 Product: e501)',
        'Linux',
        new GamepadMapping(
            /* dpadUp */ new AxisAsButton(-2),
            /* dpadDown */ new AxisAsButton(2),
            /* dpadLeft */ new AxisAsButton(-1),
            /* dpadRight */ new AxisAsButton(1),
            /* menu */ 10,
            /* button0 */ 2,
            /* button1 */ 3,
            /* button2 */ 1,
            /* button3 */ 4,
            /* leftStickUp */ undefined,
            /* leftStickDown */ undefined,
            /* leftStickLeft */ undefined,
            /* leftStickRight */ undefined,
            /* rightStickUp */ undefined,
            /* rightStickDown */ undefined,
            /* rightStickLeft */ undefined,
            /* rightStickRight */ undefined,
            /* leftShoulder */ 5,
            /* rightShoulder */ 6,
            /* leftTrigger */ undefined,
            /* rightTrigger */ undefined
        )),
    new GameInputModel(
        GameInputSchema.Plumber,
        'nintendo-generic',
        '0810-e501-usb gamepad           ',
        'Linux',
        new GamepadMapping(
            /* dpadUp */ new AxisAsButton(-2),
            /* dpadDown */ new AxisAsButton(2),
            /* dpadLeft */ new AxisAsButton(-1),
            /* dpadRight */ new AxisAsButton(1),
            /* menu */ 10,
            /* button0 */ 2,
            /* button1 */ 3,
            /* button2 */ 1,
            /* button3 */ 4,
            /* leftStickUp */ undefined,
            /* leftStickDown */ undefined,
            /* leftStickLeft */ undefined,
            /* leftStickRight */ undefined,
            /* rightStickUp */ undefined,
            /* rightStickDown */ undefined,
            /* rightStickLeft */ undefined,
            /* rightStickRight */ undefined,
            /* leftShoulder */ 5,
            /* rightShoulder */ 6,
            /* leftTrigger */ undefined,
            /* rightTrigger */ undefined
        )),
    new GameInputModel(
        GameInputSchema.Plumber,
        'nintendo-generic',
        'usb gamepad            (Vendor: 0810 Product: e501)',
        'macOS',
        new GamepadMapping(
            /* dpadUp */ new AxisAsButton(-2),
            /* dpadDown */ new AxisAsButton(2),
            /* dpadLeft */ new AxisAsButton(-1),
            /* dpadRight */ new AxisAsButton(1),
            /* menu */ 10,
            /* button0 */ 2,
            /* button1 */ 3,
            /* button2 */ 1,
            /* button3 */ 4,
            /* leftStickUp */ undefined,
            /* leftStickDown */ undefined,
            /* leftStickLeft */ undefined,
            /* leftStickRight */ undefined,
            /* rightStickUp */ undefined,
            /* rightStickDown */ undefined,
            /* rightStickLeft */ undefined,
            /* rightStickRight */ undefined,
            /* leftShoulder */ 5,
            /* rightShoulder */ 6,
            /* leftTrigger */ undefined,
            /* rightTrigger */ undefined
        )),
    new GameInputModel(
        GameInputSchema.Plumber,
        'nintendo-generic',
        '810-e501-usb gamepad           ',
        'macOS',
        new GamepadMapping(
            /* dpadUp */ new AxisAsButton(-3),
            /* dpadDown */ new AxisAsButton(3),
            /* dpadLeft */ new AxisAsButton(-2),
            /* dpadRight */ new AxisAsButton(2),
            /* menu */ 10,
            /* button0 */ 2,
            /* button1 */ 3,
            /* button2 */ 1,
            /* button3 */ 4,
            /* leftStickUp */ undefined,
            /* leftStickDown */ undefined,
            /* leftStickLeft */ undefined,
            /* leftStickRight */ undefined,
            /* rightStickUp */ undefined,
            /* rightStickDown */ undefined,
            /* rightStickLeft */ undefined,
            /* rightStickRight */ undefined,
            /* leftShoulder */ 5,
            /* rightShoulder */ 6,
            /* leftTrigger */ undefined,
            /* rightTrigger */ undefined
        )),
    new GameInputModel(
        GameInputSchema.Hedgehog,
        'generic',
        'Gravis GamePad Pro USB  (Vendor: 0428 Product: 4001)',
        'Linux',
        GravisGamepadProSchema),
    new GameInputModel(
        GameInputSchema.Hedgehog,
        'generic',
        '0428-4001-Gravis GamePad Pro USB ',
        'Linux',
        GravisGamepadProSchema),
    new GameInputModel(
        GameInputSchema.Hedgehog,
        'generic',
        'GamePad Pro USB  (Vendor: 0428 Product: 4001)',
        'macOS',
        GravisGamepadProSchema),
    new GameInputModel(
        GameInputSchema.Hedgehog,
        'generic',
        '428-4001-GamePad Pro USB ',
        'macOS',
        GravisGamepadProSchema),
    new GameInputModel(
        GameInputSchema.Hedgehog,
        'xboxone',
        'Xbox Wireless Controller (STANDARD GAMEPAD Vendor: 045e Product: 02e0)',
        'Linux'
    ),
    new GameInputModel(
        GameInputSchema.Hedgehog,
        'xboxone',
        'Microsoft Controller (STANDARD GAMEPAD Vendor: 045e Product: 0b12)',
        'Linux'
    ),
    new GameInputModel(
        GameInputSchema.Hedgehog,
        'xboxone',
        'Xbox Wireless Controller (STANDARD GAMEPAD Vendor: 045e Product: 0b13)',
        'Android'
    ),
    new GameInputModel(
        GameInputSchema.Hedgehog,
        'xboxone',
        'Performance Designed Products Afterglow Wired Controller for Xbox One (STANDARD GAMEPAD Vendor: 0e6f Product: 0139)',
        'Linux'
    ),
    new GameInputModel(
        GameInputSchema.Hedgehog,
        'xboxone',
        'Performance Designed Products Afterglow Wired Controller for Xbox One (Vendor: 0e6f Product: 0139)',
        'Linux',
        new GamepadMapping(
            /* dpadUp */ new AxisAsButton(-8),
            /* dpadDown */ new AxisAsButton(8),
            /* dpadLeft */ new AxisAsButton(-7),
            /* dpadRight */ new AxisAsButton(7),
            /* menu */ 8,
            /* button0 */ 1,
            /* button1 */ 2,
            /* button2 */ 3,
            /* button3 */ 4,
            /* leftStickUp */ new AxisAsButton(-2),
            /* leftStickDown */ new AxisAsButton(2),
            /* leftStickLeft */ new AxisAsButton(-1),
            /* leftStickRight */ new AxisAsButton(1),
            /* rightStickUp */ new AxisAsButton(-5),
            /* rightStickDown */ new AxisAsButton(5),
            /* rightStickLeft */ new AxisAsButton(-4),
            /* rightStickRight */ new AxisAsButton(4),
            /* leftShoulder */ 5,
            /* rightShoulder */ 6,
            /* leftTrigger */ new AxisAsButton(3),
            /* rightTrigger */ new AxisAsButton(6)
        )),
    new GameInputModel(
        GameInputSchema.Hedgehog,
        'xboxone',
        '0e6f-0139-Afterglow Prismatic Wired Controller',
        'Linux',
        new GamepadMapping(
            /* dpadUp */ new AxisAsButton(-8),
            /* dpadDown */ new AxisAsButton(8),
            /* dpadLeft */ new AxisAsButton(-7),
            /* dpadRight */ new AxisAsButton(7),
            /* menu */ 8,
            /* button0 */ 1,
            /* button1 */ 2,
            /* button2 */ 3,
            /* button3 */ 4,
            /* leftStickUp */ new AxisAsButton(-2),
            /* leftStickDown */ new AxisAsButton(2),
            /* leftStickLeft */ new AxisAsButton(-1),
            /* leftStickRight */ new AxisAsButton(1),
            /* rightStickUp */ new AxisAsButton(-5),
            /* rightStickDown */ new AxisAsButton(5),
            /* rightStickLeft */ new AxisAsButton(-4),
            /* rightStickRight */ new AxisAsButton(4),
            /* leftShoulder */ 5,
            /* rightShoulder */ 6,
            /* leftTrigger */ new AxisAsButton(3),
            /* rightTrigger */ new AxisAsButton(6)
        )),
    new GameInputModel(
        GameInputSchema.Plumber,
        'nintendo-generic',
        'USB,2-axis 8-button gamepad   (STANDARD GAMEPAD Vendor: 0583 Product: 2060)',
        'macOS',
        new GamepadMapping(
            /* dpadUp */ 13,
            /* dpadDown */ 14,
            /* dpadLeft */ 15,
            /* dpadRight */ 16,
            /* menu */ 10,
            /* button0 */ 2,
            /* button1 */ 1,
            /* button2 */ 4,
            /* button3 */ 3,
            /* leftStickUp */ undefined,
            /* leftStickDown */ undefined,
            /* leftStickLeft */ undefined,
            /* leftStickRight */ undefined,
            /* rightStickUp */ undefined,
            /* rightStickDown */ undefined,
            /* rightStickLeft */ undefined,
            /* rightStickRight */ undefined,
            /* leftShoulder */ 5,
            /* rightShoulder */ 6,
            /* leftTrigger */ undefined,
            /* rightTrigger */ undefined
        )),
    new GameInputModel(
        GameInputSchema.Plumber,
        'nintendo-generic',
        '0583-2060-USB,2-axis 8-button gamepad   ',
        'macOS',
        new GamepadMapping(
            /* dpadUp */ 13,
            /* dpadDown */ 14,
            /* dpadLeft */ 15,
            /* dpadRight */ 16,
            /* menu */ 10,
            /* button0 */ 2,
            /* button1 */ 1,
            /* button2 */ 4,
            /* button3 */ 3,
            /* leftStickUp */ undefined,
            /* leftStickDown */ undefined,
            /* leftStickLeft */ undefined,
            /* leftStickRight */ undefined,
            /* rightStickUp */ undefined,
            /* rightStickDown */ undefined,
            /* rightStickLeft */ undefined,
            /* rightStickRight */ undefined,
            /* leftShoulder */ 5,
            /* rightShoulder */ 6,
            /* leftTrigger */ undefined,
            /* rightTrigger */ undefined
        )),
    new GameInputModel(
        GameInputSchema.Plumber, // it's a square and x /y are generic style, while a / b are nintendo style - FAMICOM
        'nintendo-generic',
        'BUFFALO BGC-FC801 USB Gamepad (Vendor: 0411 Product: 00c6)',
        'macOS',
        new GamepadMapping(
            /* dpadUp */ new AxisAsButton(-2),
            /* dpadDown */ new AxisAsButton(2),
            /* dpadLeft */ new AxisAsButton(-1),
            /* dpadRight */ new AxisAsButton(1),
            /* menu */ 8,
            /* button0 */ 1,
            /* button1 */ 2,
            /* button2 */ 3,
            /* button3 */ 4,
            /* leftStickUp */ undefined,
            /* leftStickDown */ undefined,
            /* leftStickLeft */ undefined,
            /* leftStickRight */ undefined,
            /* rightStickUp */ undefined,
            /* rightStickDown */ undefined,
            /* rightStickLeft */ undefined,
            /* rightStickRight */ undefined,
            /* leftShoulder */ 5,
            /* rightShoulder */ 6,
            /* leftTrigger */ undefined,
            /* rightTrigger */ undefined
        )),
    new GameInputModel(
        GameInputSchema.Plumber, // it's a square and x /y are generic style, while a / b are nintendo style - FAMICOM
        'nintendo-generic',
        '0411-00c6-BUFFALO BGC-FC801 USB Gamepad ',
        'macOS',
        new GamepadMapping(
            /* dpadUp */ new AxisAsButton(-2),
            /* dpadDown */ new AxisAsButton(2),
            /* dpadLeft */ new AxisAsButton(-1),
            /* dpadRight */ new AxisAsButton(1),
            /* menu */ 8,
            /* button0 */ 1,
            /* button1 */ 2,
            /* button2 */ 3,
            /* button3 */ 4,
            /* leftStickUp */ undefined,
            /* leftStickDown */ undefined,
            /* leftStickLeft */ undefined,
            /* leftStickRight */ undefined,
            /* rightStickUp */ undefined,
            /* rightStickDown */ undefined,
            /* rightStickLeft */ undefined,
            /* rightStickRight */ undefined,
            /* leftShoulder */ 5,
            /* rightShoulder */ 6,
            /* leftTrigger */ undefined,
            /* rightTrigger */ undefined
        )),
    new GameInputModel(
        GameInputSchema.Hedgehog, // should be numbers, see issue #16
        'generic',
        'USB  Joystick (Vendor: 1345 Product: 1030)',
        'macOS',
        new GamepadMapping(
            /* dpadUp */ new AxisAsButton(-2),
            /* dpadDown */ new AxisAsButton(2),
            /* dpadLeft */ new AxisAsButton(-1),
            /* dpadRight */ new AxisAsButton(1),
            /* menu */ 10,
            /* button0 */ 3,
            /* button1 */ 2,
            /* button2 */ 4,
            /* button3 */ 1,
            /* leftStickUp */ undefined,
            /* leftStickDown */ undefined,
            /* leftStickLeft */ undefined,
            /* leftStickRight */ undefined,
            /* rightStickUp */ undefined,
            /* rightStickDown */ undefined,
            /* rightStickLeft */ undefined,
            /* rightStickRight */ undefined,
            /* leftShoulder */ 5,
            /* rightShoulder */ 6,
            /* leftTrigger */ 7,
            /* rightTrigger */ 8
        )),
    new GameInputModel(
        GameInputSchema.Hedgehog, // should be numbers, see issue #16
        'generic',
        '1345-1030-USB  Joystick ',
        'macOS',
        new GamepadMapping(
            /* dpadUp */ new AxisAsButton(-2),
            /* dpadDown */ new AxisAsButton(2),
            /* dpadLeft */ new AxisAsButton(-1),
            /* dpadRight */ new AxisAsButton(1),
            /* menu */ 10,
            /* button0 */ 3,
            /* button1 */ 2,
            /* button2 */ 4,
            /* button3 */ 1,
            /* leftStickUp */ undefined,
            /* leftStickDown */ undefined,
            /* leftStickLeft */ undefined,
            /* leftStickRight */ undefined,
            /* rightStickUp */ undefined,
            /* rightStickDown */ undefined,
            /* rightStickLeft */ undefined,
            /* rightStickRight */ undefined,
            /* leftShoulder */ 5,
            /* rightShoulder */ 6,
            /* leftTrigger */ 7,
            /* rightTrigger */ 8
        )),
    new GameInputModel(
        GameInputSchema.Hedgehog,
        'joystick',
        'Innovative Produtcs VR Pro 2000 USB Joystick (Vendor: 04b4 Product: 2774)',
        'Linux',
        new GamepadMapping(
            /* dpadUp */ 13,
            /* dpadDown */ 14,
            /* dpadLeft */ 15,
            /* dpadRight */ 16,
            /* menu */ 4,
            /* button0 */ 1,
            /* button1 */ 2,
            /* button2 */ 3,
            /* button3 */ new AxisAsButton(-3, frenchVRStickThreshold, frenchVRStickDeadzone),
            /* leftStickUp */ new AxisAsButton(2, frenchVRStickThreshold, frenchVRStickDeadzone),
            /* leftStickDown */ new AxisAsButton(-2, frenchVRStickThreshold, frenchVRStickDeadzone),
            /* leftStickLeft */ new AxisAsButton(1, frenchVRStickThreshold, frenchVRStickDeadzone),
            /* leftStickRight */ new AxisAsButton(-1, frenchVRStickThreshold, frenchVRStickDeadzone),
            /* rightStickUp */ new AxisAsButton(-6, frenchVRStickThreshold, frenchVRStickDeadzone),
            /* rightStickDown */ new AxisAsButton(6, frenchVRStickThreshold, frenchVRStickDeadzone),
            /* rightStickLeft */ new AxisAsButton(-5, frenchVRStickThreshold, frenchVRStickDeadzone),
            /* rightStickRight */ new AxisAsButton(5, frenchVRStickThreshold, frenchVRStickDeadzone),
            /* leftShoulder */ 5,
            /* rightShoulder */ 6,
            /* leftTrigger */ 7,
            /* rightTrigger */ 8
        )),
    new GameInputModel(
        GameInputSchema.Hedgehog,
        'joystick',
        '04b4-2774-Innovative Produtcs VR Pro 2000 USB Joystick',
        'Linux',
        new GamepadMapping(
            /* dpadUp */ 13,
            /* dpadDown */ 14,
            /* dpadLeft */ 15,
            /* dpadRight */ 16,
            /* menu */ 4,
            /* button0 */ 1,
            /* button1 */ 2,
            /* button2 */ 3,
            /* button3 */ new AxisAsButton(-3, frenchVRStickThreshold, frenchVRStickDeadzone),
            /* leftStickUp */ new AxisAsButton(2, frenchVRStickThreshold, frenchVRStickDeadzone),
            /* leftStickDown */ new AxisAsButton(-2, frenchVRStickThreshold, frenchVRStickDeadzone),
            /* leftStickLeft */ new AxisAsButton(1, frenchVRStickThreshold, frenchVRStickDeadzone),
            /* leftStickRight */ new AxisAsButton(-1, frenchVRStickThreshold, frenchVRStickDeadzone),
            /* rightStickUp */ new AxisAsButton(-6, frenchVRStickThreshold, frenchVRStickDeadzone),
            /* rightStickDown */ new AxisAsButton(6, frenchVRStickThreshold, frenchVRStickDeadzone),
            /* rightStickLeft */ new AxisAsButton(-5, frenchVRStickThreshold, frenchVRStickDeadzone),
            /* rightStickRight */ new AxisAsButton(5, frenchVRStickThreshold, frenchVRStickDeadzone),
            /* leftShoulder */ 5,
            /* rightShoulder */ 6,
            /* leftTrigger */ 7,
            /* rightTrigger */ 8
        )),
    new GameInputModel(
        GameInputSchema.Plumber,
        'nintendo-generic',
        '20d6-a711-Bensussen Deutsch & Associates,Inc.(BDA) Core (Plus) Wired Controller',
        'Linux',
        new GamepadMapping(
            /* dpadUp */ new AxisAsButton(-6),
            /* dpadDown */ new AxisAsButton(6),
            /* dpadLeft */ new AxisAsButton(-5),
            /* dpadRight */ new AxisAsButton(5),
            /* menu */ 10,
            /* button0 */ 3,
            /* button1 */ 2,
            /* button2 */ 4,
            /* button3 */ 1,
            /* leftStickUp */ new AxisAsButton(-2),
            /* leftStickDown */ new AxisAsButton(2),
            /* leftStickLeft */ new AxisAsButton(-1),
            /* leftStickRight */ new AxisAsButton(1),
            /* rightStickUp */ new AxisAsButton(-4),
            /* rightStickDown */ new AxisAsButton(4),
            /* rightStickLeft */ new AxisAsButton(-3),
            /* rightStickRight */ new AxisAsButton(3),
            /* leftShoulder */ 5,
            /* rightShoulder */ 6,
            /* leftTrigger */ 7,
            /* rightTrigger */ 8
        )
    ),
    new GameInputModel(
        GameInputSchema.Plumber,
        'nintendo-generic',
        'Bensussen Deutsch & Associates,Inc.(BDA) Core (Plus) Wired Controller (Vendor: 20d6 Product: a711)',
        'Linux',
        new GamepadMapping(
            /* dpadUp */ new AxisAsButton(-6),
            /* dpadDown */ new AxisAsButton(6),
            /* dpadLeft */ new AxisAsButton(-5),
            /* dpadRight */ new AxisAsButton(5),
            /* menu */ 10,
            /* button0 */ 3,
            /* button1 */ 2,
            /* button2 */ 4,
            /* button3 */ 1,
            /* leftStickUp */ new AxisAsButton(-2),
            /* leftStickDown */ new AxisAsButton(2),
            /* leftStickLeft */ new AxisAsButton(-1),
            /* leftStickRight */ new AxisAsButton(1),
            /* rightStickUp */ new AxisAsButton(-4),
            /* rightStickDown */ new AxisAsButton(4),
            /* rightStickLeft */ new AxisAsButton(-3),
            /* rightStickRight */ new AxisAsButton(3),
            /* leftShoulder */ 5,
            /* rightShoulder */ 6,
            /* leftTrigger */ 7,
            /* rightTrigger */ 8
        )
    ),
    new GameInputModel(
        GameInputSchema.Plumber,
        'nintendo-generic',
        'Core (Plus) Wired Controller (Vendor: 20d6 Product: a711)',
        'Windows',
        new GamepadMapping(
            undefined, undefined, undefined, undefined,
            10,
            3, 2, 4, 1,
            new AxisAsButton(-2),
            new AxisAsButton(2),
            new AxisAsButton(-1),
            new AxisAsButton(1),
            new AxisAsButton(-6),
            new AxisAsButton(6),
            new AxisAsButton(-3),
            new AxisAsButton(3),
            5, 6, 7, 8
        )
    )
]

export default GameInputModels
export { GameInputModels, GravisGamepadProSchema }
