name: CI Build

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    - name: Build
      run: |
        npm ci
        npm run build-prod

    - name: Test
      run: npm test

    - name: Package
      uses: actions/upload-artifact@v4
      with:
        name: release
        path: dist/*
