name: NodeJS with Webpack

on:
  pull_request:
    branches: [ "master" ]
  release:
    types: [ "published" ]
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm ci
        npm run build

    - uses: actions/upload-artifact@v3
      with:
        path: |
          LICENSE
          dist
          docs
