name: NodeJS with Webpack

on:
  pull_request:
    branches: [ "master" ]
  release:
    types: [ "published" ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm ci
        npx webpack --config webpack.config.js --mode production
